const endpoints = {
  auth: {
    login: '/auth/admin/login',
    sendOtp: '/auth/admin/send-otp',
    verifyOtp: '/auth/admin/verify-otp',
    logout: '/auth/admin/logout',
  },
  category: {
    list: '/categories',
    parents: '/categories/parents',
    subcategories: (parentId: string) => `/categories/${parentId}/subcategories`,
    details: (id: string) => `/categories/${id}`,
  },
  role: {
    create: '/rbac/roles',
    list: '/rbac/roles',
    details: (id: string) => `/rbac/roles/${id}`,
    update: (id: string) => `/rbac/roles/${id}`,
    delete: (id: string) => `/rbac/roles/${id}`,
    assignPermissions: (id: string) => `/rbac/roles/${id}/permissions`,
  },
  permission: {
    list: '/rbac/permissions',
    create: '/rbac/permissions',
    details: (id: string) => `/rbac/permissions/${id}`,
  },
  user: {
    create: '/admin/admins',
    list: '/admin/users',
    details: (id: string) => `/admin/users/${id}`,
    update: (id: string) => `/admin/users/${id}`,
    updateStatus: (id: string) => `/admin/users/${id}/status`,
    updateRole: (id: string) => `/admin/users/${id}/role`,
    delete: (id: string) => `/admin/users/${id}`,
    restore: (id: string) => `/admin/users/restore/${id}`,
  },
  member: {
    create: '/admin/member',
    list: '/admin/member/list',
    details: (id: string) => `/admin/member/${id}`,
    update: (id: string) => `/admin/member/${id}`,
    delete: (id: string) => `/admin/member/${id}`,
    restore: (id: string) => `/admin/member/restore/${id}`,
  },
  post: {
    create: '/admin/post',
    list: '/admin/post/list',
    details: (id: string) => `/admin/post/${id}`,
    update: (id: string) => `/admin/post/${id}`,
    delete: (id: string) => `/admin/post/${id}`,
    approve: (id: string) => `/admin/post/${id}/approve`,
    reject: (id: string) => `/admin/post/${id}/reject`,
  },
  moderation: {
    list: '/admin/moderation/list',
    approve: (id: string) => `/admin/moderation/${id}/approve`,
    reject: (id: string) => `/admin/moderation/${id}/reject`,
    details: (id: string) => `/admin/moderation/${id}`,
  },
  dashboard: {
    stats: '/admin/dashboard/stats',
    recentActivity: '/admin/dashboard/recent-activity',
    analytics: '/admin/dashboard/analytics',
  },
  attachment: {
    upload: '/admin/attachment/upload',
    view: (fileName: string) => `/attachment/view/${fileName}`,
    delete: '/admin/attachment/delete',
  },
  employer: {
    create: '/admin/employers',
    list: '/admin/employers',
    details: (id: string) => `/admin/employers/${id}`,
    update: (id: string) => `/admin/employers/${id}`,
    delete: (id: string) => `/admin/employers/${id}`,
  },
  candidate: {
    create: '/admin/users',
    list: '/admin/users',
    details: (id: string) => `/admin/users/${id}`,
    update: (id: string) => `/admin/users/${id}`,
    delete: (id: string) => `/admin/users/${id}`,
  },
  company: {
    create: '/companies',
    list: '/companies',
    me: '/companies/me',
    details: (id: string) => `/companies/${id}`,
    detailsBySlug: (slug: string) => `/companies/slug/${slug}`,
    update: (id: string) => `/companies/${id}`,
    delete: (id: string) => `/companies/${id}`,
    uploadLogo: (id: string) => `/companies/${id}/logo`,
    uploadBanner: (id: string) => `/companies/${id}/banner`,
    uploadVerificationDocument: (id: string) => `/companies/${id}/verification-document`,
    // Admin-specific endpoints (for admin's own company)
    adminProfile: '/companies/admin/profile',
    updateAdminProfile: '/companies/admin/profile',
  },
  resumeTemplates: {
    create: '/resume-templates',
    list: '/resume-templates',
    details: (id: string) => `/resume-templates/${id}`,
    update: (id: string) => `/resume-templates/${id}`,
    delete: (id: string) => `/resume-templates/${id}`,
    uploadThumbnail: (id: string) => `/resume-templates/${id}/thumbnail`,
    updateStatus: (id: string) => `/resume-templates/${id}/status`,
    updateOrder: (id: string) => `/resume-templates/${id}/order`,
  },
  videoResume: {
    list: '/admin/videos',
    updateStatus: (profileId: string) => `/admin/profile/${profileId}/video/status`,
  },
  skills: {
    list: '/master-data/skills',
    create: '/skills',
    update: (id: string) => `/skills/${id}`,
    delete: (id: string) => `/skills/${id}`,
  },
  degrees: {
    list: '/master-data/degrees',
    create: '/master-data/degrees',
    update: (id: string) => `/master-data/degrees/${id}`,
    delete: (id: string) => `/master-data/degrees/${id}`,
    fieldsOfStudy: (degreeId: string) => `/master-data/degrees/${degreeId}/fields-of-study`,
  },
  fieldsOfStudy: {
    create: (degreeId: string) => `/master-data/degrees/${degreeId}/fields-of-study`,
    update: (id: string) => `/master-data/fields-of-study/${id}`,
    delete: (id: string) => `/master-data/fields-of-study/${id}`,
  },
  avatars: {
    create: '/avatars',
    list: '/avatars',
    details: (id: string) => `/avatars/${id}`,
    update: (id: string) => `/avatars/${id}`,
    updateStatus: (id: string) => `/avatars/${id}/status`,
    updateOrder: (id: string) => `/avatars/${id}/order`,
    updateImage: (id: string) => `/avatars/${id}/image`,
    delete: (id: string) => `/avatars/${id}`,
  },
  filterOptions: {
    list: '/admin/filter-options',
    create: '/admin/filter-options',
    update: (id: string) => `/admin/filter-options/${id}`,
    delete: (id: string) => `/admin/filter-options/${id}`,
  },
};

export default endpoints;
